name: Hello World

on: 
    workflow_dispatch:
    push:
        branches:
            - main    

jobs:
    say-hello-inline-bash:
        runs-on: ubuntu-latest        
        steps:
            - name: Say Hello
              run: echo "Hello, World!"
    
    say-hello-in-python:
        runs-on: ubuntu-latest        
        steps:
            - name: Say Hello in Python
              run: |
                echo "print('Hello, World!')" > hello.py
                python3 hello.py

    say-hello-in-javascript:
        runs-on: ubuntu-latest        
        steps:
            - name: Say Hello in JavaScript
              uses: actions/hello-world-javascript-action@v1
              with:
                who-to-greet: 'World'    
                    